import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Download, FileText, Rocket, Building2, Code2, BookOpen, Crown, Lock } from "lucide-react";
import { toast } from "sonner";

interface ExportTemplateModalProps {
  open: boolean;
  onClose: () => void;
  content: string;
}

type TemplateId = "minimal" | "startup" | "enterprise" | "opensource" | "api" | "onboarding";

interface Template {
  id: TemplateId;
  name: string;
  description: string;
  icon: React.ElementType;
  premium: boolean;
  accent: string;
  bgColor: string;
  textColor: string;
  codeTheme: string;
}

const templates: Template[] = [
  {
    id: "minimal",
    name: "Minimal Clean",
    description: "Simple, elegant docs with a clean sans-serif style.",
    icon: FileText,
    premium: false,
    accent: "#22d3ee",
    bgColor: "#ffffff",
    textColor: "#1a1a2e",
    codeTheme: "#f8f9fa",
  },
  {
    id: "startup",
    name: "Startup Bold",
    description: "Vibrant gradient headers, perfect for landing pages & pitch decks.",
    icon: Rocket,
    premium: false,
    accent: "#8b5cf6",
    bgColor: "#0f0f23",
    textColor: "#e2e8f0",
    codeTheme: "#1e1e3f",
  },
  {
    id: "enterprise",
    name: "Enterprise Pro",
    description: "Professional corporate layout with table of contents and branding.",
    icon: Building2,
    premium: true,
    accent: "#0ea5e9",
    bgColor: "#ffffff",
    textColor: "#1e293b",
    codeTheme: "#f1f5f9",
  },
  {
    id: "opensource",
    name: "Open Source",
    description: "GitHub-style docs with badges, contribution guide, and license section.",
    icon: Code2,
    premium: false,
    accent: "#10b981",
    bgColor: "#0d1117",
    textColor: "#c9d1d9",
    codeTheme: "#161b22",
  },
  {
    id: "api",
    name: "API Reference",
    description: "Endpoint tables, request/response blocks, and auth sections.",
    icon: BookOpen,
    premium: true,
    accent: "#f59e0b",
    bgColor: "#18181b",
    textColor: "#e4e4e7",
    codeTheme: "#27272a",
  },
  {
    id: "onboarding",
    name: "Developer Onboarding",
    description: "Step-by-step setup guide with prerequisites, install, and run instructions.",
    icon: Rocket,
    premium: true,
    accent: "#ec4899",
    bgColor: "#fdf2f8",
    textColor: "#1e1b4b",
    codeTheme: "#fce7f3",
  },
];

const buildHtml = (content: string, template: Template): string => {
  const escapedContent = content.replace(/</g, "&lt;").replace(/>/g, "&gt;");
  
  const tocScript = template.id === "enterprise" ? `
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var headings = document.querySelectorAll('h2, h3');
        var toc = document.getElementById('toc');
        if (toc && headings.length) {
          headings.forEach(function(h, i) {
            h.id = 'section-' + i;
            var a = document.createElement('a');
            a.href = '#section-' + i;
            a.textContent = h.textContent;
            a.style.display = 'block';
            a.style.padding = '4px 0';
            a.style.color = '${template.accent}';
            a.style.fontSize = h.tagName === 'H3' ? '13px' : '14px';
            a.style.paddingLeft = h.tagName === 'H3' ? '16px' : '0';
            toc.appendChild(a);
          });
        }
      });
    </script>` : "";

  const tocHtml = template.id === "enterprise" ? `
    <nav style="background:${template.codeTheme};padding:1.5rem;border-radius:8px;margin-bottom:2rem;">
      <h3 style="font-size:14px;text-transform:uppercase;letter-spacing:2px;color:${template.accent};margin-bottom:12px;">Table of Contents</h3>
      <div id="toc"></div>
    </nav>` : "";

  const badgesHtml = template.id === "opensource" ? `
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:24px;">
      <img src="https://img.shields.io/badge/license-MIT-green" alt="MIT License" />
      <img src="https://img.shields.io/badge/PRs-welcome-brightgreen" alt="PRs Welcome" />
      <img src="https://img.shields.io/badge/docs-AutoDoc%20AI-blue" alt="AutoDoc AI" />
    </div>` : "";

  const footerHtml = `
    <footer style="margin-top:4rem;padding-top:2rem;border-top:1px solid ${template.accent}33;text-align:center;font-size:12px;color:${template.textColor}88;">
      Generated by <strong>AutoDoc AI</strong> — Codebase Intelligence Platform
    </footer>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Documentation — ${template.name} Template</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: ${template.bgColor}; color: ${template.textColor}; line-height: 1.7; }
    .container { max-width: 860px; margin: 0 auto; padding: 3rem 2rem; }
    h1 { font-size: 2.4rem; font-weight: 800; margin-bottom: 0.5rem; ${template.id === "startup" ? `background: linear-gradient(135deg, ${template.accent}, #ec4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent;` : `color: ${template.accent};`} }
    h2 { font-size: 1.6rem; font-weight: 700; margin-top: 2.5rem; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid ${template.accent}33; }
    h3 { font-size: 1.2rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.75rem; }
    p { margin-bottom: 1rem; }
    a { color: ${template.accent}; text-decoration: none; }
    a:hover { text-decoration: underline; }
    pre { background: ${template.codeTheme}; padding: 1.25rem; border-radius: 8px; overflow-x: auto; font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 13px; line-height: 1.5; margin: 1rem 0; border: 1px solid ${template.accent}22; }
    code { background: ${template.codeTheme}; padding: 2px 8px; border-radius: 4px; font-family: 'JetBrains Mono', monospace; font-size: 13px; }
    ul, ol { margin: 1rem 0; padding-left: 1.5rem; }
    li { margin-bottom: 0.4rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 10px 14px; text-align: left; border: 1px solid ${template.accent}22; }
    th { background: ${template.codeTheme}; font-weight: 600; }
    blockquote { border-left: 4px solid ${template.accent}; padding: 0.75rem 1rem; margin: 1rem 0; background: ${template.codeTheme}; border-radius: 0 6px 6px 0; }
    img { max-width: 100%; border-radius: 8px; }
    hr { border: none; border-top: 1px solid ${template.accent}33; margin: 2rem 0; }
    @media print { body { font-size: 12pt; } .container { max-width: 100%; padding: 0; } }
  </style>
  ${tocScript}
</head>
<body>
  <div class="container">
    ${badgesHtml}
    ${tocHtml}
    <pre style="white-space:pre-wrap;word-wrap:break-word;border:none;background:transparent;font-family:inherit;font-size:inherit;padding:0;">${escapedContent}</pre>
    ${footerHtml}
  </div>
</body>
</html>`;
};

const ExportTemplateModal = ({ open, onClose, content }: ExportTemplateModalProps) => {
  const [selected, setSelected] = useState<TemplateId>("minimal");

  const handleExport = (template: Template) => {
    if (template.premium) {
      toast.error("Upgrade to Pro to unlock this template!", {
        action: { label: "Upgrade", onClick: () => window.location.href = "/payment" },
      });
      return;
    }
    const html = buildHtml(content, template);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `docs-${template.id}.html`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Exported with ${template.name} template!`);
    onClose();
  };

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm"
          onClick={onClose}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="w-full max-w-3xl rounded-2xl border border-border bg-card p-6 shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-6">
              <div>
                <h2 className="text-xl font-bold text-foreground">Export with Template</h2>
                <p className="text-sm text-muted-foreground mt-1">Choose a professional template for your documentation</p>
              </div>
              <button onClick={onClose} className="text-muted-foreground hover:text-foreground transition-colors">
                <X size={20} />
              </button>
            </div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mb-6">
              {templates.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setSelected(t.id)}
                  className={`relative p-4 rounded-xl border text-left transition-all ${
                    selected === t.id
                      ? "border-primary bg-primary/5 ring-1 ring-primary/30"
                      : "border-border hover:border-primary/30 hover:bg-secondary/30"
                  }`}
                >
                  {t.premium && (
                    <div className="absolute top-2 right-2">
                      <Crown size={14} className="text-amber-400" />
                    </div>
                  )}
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center mb-3" style={{ background: `${t.accent}20` }}>
                    <t.icon size={16} style={{ color: t.accent }} />
                  </div>
                  <h3 className="font-semibold text-sm text-foreground">{t.name}</h3>
                  <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{t.description}</p>
                  {/* Color preview */}
                  <div className="flex gap-1 mt-3">
                    <div className="w-4 h-4 rounded-full border border-border" style={{ background: t.bgColor }} />
                    <div className="w-4 h-4 rounded-full border border-border" style={{ background: t.accent }} />
                    <div className="w-4 h-4 rounded-full border border-border" style={{ background: t.codeTheme }} />
                  </div>
                </button>
              ))}
            </div>

            <div className="flex gap-3 justify-end">
              <button
                onClick={onClose}
                className="px-5 py-2.5 rounded-lg border border-border text-foreground hover:bg-secondary transition-colors text-sm"
              >
                Cancel
              </button>
              <button
                onClick={() => handleExport(templates.find((t) => t.id === selected)!)}
                className="px-6 py-2.5 rounded-lg bg-primary text-primary-foreground font-semibold hover:opacity-90 transition-all text-sm flex items-center gap-2 glow-primary"
              >
                {templates.find((t) => t.id === selected)?.premium ? (
                  <><Lock size={14} /> Pro Only</>
                ) : (
                  <><Download size={14} /> Export</>
                )}
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default ExportTemplateModal;
